/*
 * This source file was generated by the Gradle 'init' task
 */
package org.app;

import java.net.*;

public class App {
    public static void main(String[] args) {
        info();
        Location userLocation = UserInput.userInput(System.in);
        URL apiURL = Request.parseURl(userLocation);

        if (apiURL == null){
            System.out.println("API Url is null");
            return;
        }

        String response = Request.apiRequest(apiURL);

        System.out.println("RESPONSE: " + response);

        if (response == null){
            System.out.println("API Response is null");
            return;
        }

        dataOutput(response);
    }

    private static void info() {
        System.out.println("");
        System.out.println("APP STARTED");
        System.out.println("Provide longitude and latitude for location of Sunset");
    } 

    private static void dataOutput(String inputLine){
        APIData apiData = new APIData(JSONParse.getJSON(inputLine));
        System.out.println("Your sunrise will be at: " + apiData.getSunrise());
        System.out.println("Your sunset will be at: " + apiData.getSunset());

    }
}

